### PR TITLE
added clone methods for device

### PR DESCRIPTION
**Pull request by stonneau**

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
Thank you for this contribution.
However, I have a few comments.
1. protected methods init or initCopy are meant to initialize a weak pointer to the object itself. It should not do much more. It is a good practice to implement clone through a copy constructor that handles most of the work. This way, deriving the class makes it easier to reimplement the clone method.
2. it would be nice to add a few lines of comment for internal methods defined in device.cc: CloneJointRec, CloneDisabledPositions,...

**Comment by stonneau** [comment]
1. It is not possible to initialize correctly the Device in the copy constructor,
because of the used pattern. Indeed, the root joint needs to be associated with a weak pointer
on the Device instance, which only exists after the "init" call has been made, thus after the copy constructor has returned.

An alternative is to replace the weakptr used in the joint with a simple pointer to the device instance. (After all the weakptr is not really useful in this case).

I discussed the issue with @jmirabel who preferred the present implementation. Otherwise I can do as you wish.

2.Regarding the internal methods, I think the names are explicit, but I ll add the comments required
once we decided what to do on comment 1.

Thanks

**Comment by jmirabel** [comment]
I would rather say that the design pattern is:
- one constructor doing nothing (or almost);
- one `void init(shared_ptr, args...)` per `static shared_ptr create(args...)` function, taking the same parameters plus a shared pointer to itself;
- do most of the job in `init`;

because, in this pattern, constructors will never be able to fully build an object.

To ease the implementation of clone in inherited class, a possible solution is through macros.

**Comment by florent-lamiraux** [comment]
All right, I agree with your argumentation.

**Pull request merged**
